version: "3.9"

secrets:
  grafana-client-id:
    external: true
    name: ${GRAFANA_CLIENT_ID_KEY:-grafana-client-id}
  grafana-client-secret:
    external: true
    name: ${GRAFANA_CLIENT_SECRET_KEY:-grafana-client-secret}

volumes:
  grafana-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${GRAFANA_STACK_DIR}/data

networks:
  telemetry:
    name: ${GRAFANA_NETWORK_NAME:-telemetry}

services: 
  grafana:
    container_name: grafana
    image: grafana/grafana:alpine
    environment:
      GF_INSTALL_PLUGINS: ${GRAFANA_PLUGINS}
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: DARDEUS Auth
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "false"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID__FILE: /run/secrets/grafana-client-id
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: /run/secrets/grafana-client-secret
      GF_AUTH_GENERIC_OAUTH_SCOPES: openid email profile offline_access roles
      GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH: email
      GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: username
      GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: full_name
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://auth.gyfted.io/realms/gyfted-admin/protocol/openid-connect/auth
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://auth.gyfted.io/realms/gyfted-admin/protocol/openid-connect/token
      GF_AUTH_GENERIC_OAUTH_API_URL: https://auth.gyfted.io/realms/gyfted-admin/protocol/openid-connect/userinfo
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: contains(roles[*], 'grafana_admins') && 'Admin' || contains(roles[*], 'grafana_editors') && 'Editor' || 'Viewer'
    secrets:
      - grafana-client-id
      - grafana-client-secret
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - telemetry
    ports: 
      - 3000:3000/tcp
